##Importando biblioteca Pandas e lendo as planilhas do arquivo .xlsx

In [37]:
import pandas as pd

caract_treino = pd.read_excel('dados_cientista_de_dados_envio.xlsx', sheet_name='dbo.caract_treino')
views_treino = pd.read_excel('dados_cientista_de_dados_envio.xlsx', sheet_name='dbo.materias_views_treino')
caract_novas = pd.read_excel('dados_cientista_de_dados_envio.xlsx', sheet_name='dbo.caract_novas')
views_novas = pd.read_excel('dados_cientista_de_dados_envio.xlsx', sheet_name='dbo.materias_views_novas')

##Descrição das informações para averiguar se há valores faltantes e visualização do DataFrame "caract_treino"

In [38]:
caract_treino

     codmateria                 data_pub  ... possuilinkafiliacao       tipo
0        116360  2020-11-06 14:13:24.573  ...                   0  Hard News
1        124744  2020-11-25 09:51:44.880  ...                   0  Hard News
2        129678  2020-11-04 00:00:00.000  ...                   0  Hard News
3        134805  2020-11-06 14:02:08.347  ...                   0  Hard News
4        137827  2021-01-19 16:45:14.100  ...                   0  Hard News
..          ...                      ...  ...                 ...        ...
276      215853  2021-04-24 10:00:01.003  ...                   0  Evergreen
277      215896  2021-04-21 17:00:01.450  ...                   0  Evergreen
278      215923  2021-04-21 15:00:01.543  ...                   0  Evergreen
279      216006  2021-04-25 10:00:01.593  ...                   0  Evergreen
280      216127  2021-04-24 19:00:01.350  ...                   0  Evergreen

[281 rows x 8 columns]

In [39]:
caract_treino.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 281 entries, 0 to 280
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   codmateria           281 non-null    int64
 1   data_pub             281 non-null    object
 2   titulo               281 non-null    object
 3   autor                281 non-null    int64
 4   tag                  281 non-null    object
 5   publieditorial       281 non-null    int64
 6   possuilinkafiliacao  281 non-null    int64
 7   tipo                 281 non-null    object
dtypes: int64(4), object(4)
memory usage: 17.7+ KB

##Conversão dos inteiros para strings da coluna "autor" nos DataFrames "caract_treino" e "caract_novas" para possível utilização das variáveis categóricas da coluna para o modelo de classificação

In [40]:
caract_treino['autor'] = caract_treino['autor'].apply(str)
caract_novas['autor'] = caract_novas['autor'].apply(str)

##Substituição dos valores em string da coluna "tipo" para números binários para a elaboração do modelo de classificação

In [41]:
tipo_binario = {'Evergreen': 0,
                'Hard News': 1}

caract_treino['tipo'] = caract_treino['tipo'].map(tipo_binario)
caract_treino

     codmateria                 data_pub  ... possuilinkafiliacao tipo
0        116360  2020-11-06 14:13:24.573  ...                   0    1
1        124744  2020-11-25 09:51:44.880  ...                   0    1
2        129678  2020-11-04 00:00:00.000  ...                   0    1
3        134805  2020-11-06 14:02:08.347  ...                   0    1
4        137827  2021-01-19 16:45:14.100  ...                   0    1
..          ...                      ...  ...                 ...  ...
276      215853  2021-04-24 10:00:01.003  ...                   0    0
277      215896  2021-04-21 17:00:01.450  ...                   0    0
278      215923  2021-04-21 15:00:01.543  ...                   0    0
279      216006  2021-04-25 10:00:01.593  ...                   0    0
280      216127  2021-04-24 19:00:01.350  ...                   0    0

[281 rows x 8 columns]

##Criação e visualização do DataFrame "x", o qual é o DataFrame das variáveis independentes do modelo, e da Series "y", a qual é a Series da variável dependente.

In [42]:
x = caract_treino[['autor','tag', 'publieditorial', 'possuilinkafiliacao']]
y = caract_treino['tipo']

In [43]:
print(x)

    autor            tag  publieditorial  possuilinkafiliacao
0     547      Segurança               0                    0
1     632        Mercado               0                    0
2     523        Mercado               0                    0
3     128        Mercado               0                    0
4     759       Software               0                    0
..    ...            ...             ...                  ...
276  1127       Software               0                    0
277   867       Internet               0                    0
278   805          Voxel               0                    0
279  1182  Redes Sociais               0                    0
280  1124       Internet               0                    0

[281 rows x 4 columns]

In [44]:
print(y)

0      1
1      1
2      1
3      1
4      1
      ..
276    0
277    0
278    0
279    0
280    0
Name: tipo, Length: 281, dtype: int64

##Transformação das variáveis categóricas, as quais estavam em formato string, em números binários para a elaboração do modelo de classificação, criando o DataFrame "x_dummies"

In [45]:
x_dummies = pd.get_dummies(x)
y_dummies = y

x_dummies

     publieditorial  possuilinkafiliacao  ...  tag_Software  tag_Voxel
0                 0                    0  ...             0          0
1                 0                    0  ...             0          0
2                 0                    0  ...             0          0
3                 0                    0  ...             0          0
4                 0                    0  ...             1          0
..              ...                  ...  ...           ...        ...
276               0                    0  ...             1          0
277               0                    0  ...             0          0
278               0                    0  ...             0          1
279               0                    0  ...             0          0
280               0                    0  ...             0          0

[281 rows x 57 columns]

##Criação de DataFrame com a lista de todos os autores ordenada pelo "autores_treino", através da junção dos autores dos DataFrames "caract_treino" e "caract_novas", para igualar o número de colunas do "x_dummies" e "x_novas_dummies", com o propósito de ser possível a execução do modelo de classificação e ser executado com maior precisão por conta da influência dos dados sobre os autores

In [46]:
autores_treino = caract_treino['autor'].unique().tolist()
autores_treino

['547',
 '632',
 '523',
 '128',
 '759',
 '496',
 '920',
 '932',
 '1166',
 '1054',
 '893',
 '867',
 '154',
 '775',
 '1107',
 '758',
 '1160',
 '1170',
 '1127',
 '1059',
 '1163',
 '982',
 '1047',
 '890',
 '780',
 '1124',
 '1026',
 '1010',
 '183',
 '163',
 '1164',
 '1044',
 '1157',
 '952',
 '427',
 '805',
 '1106',
 '881',
 '424',
 '1182',
 '1027',
 '468',
 '1108']

In [47]:
len(autores_treino)

43

In [48]:
autores_novas = caract_novas['autor'].unique().tolist()
autores_novas

['1107',
 '982',
 '1054',
 '1047',
 '758',
 '805',
 '1027',
 '775',
 '1059',
 '780',
 '1170',
 '1160',
 '1166',
 '1026',
 '920',
 '1010',
 '1164',
 '867',
 '893',
 '154',
 '1124',
 '932',
 '163',
 '759',
 '1127',
 '1163',
 '1155',
 '823',
 '788',
 '1106',
 '1007',
 '1102',
 '1182',
 '1041',
 '890',
 '1108']

In [49]:
len(autores_novas)

36

In [50]:
for k in range(len(autores_novas)):
  if autores_novas[k] not in autores_treino:
    autores_treino.append(autores_novas[k])
    x_dummies["autor_{}".format(autores_novas[k])] = 0

autores_treino = pd.Series(autores_treino).reset_index().drop(columns='index').rename(columns={0:'autor'})
autores_treino

   autor
0    547
1    632
2    523
3    128
4    759
5    496
6    920
7    932
8   1166
9   1054
10   893
11   867
12   154
13   775
14  1107
15   758
16  1160
17  1170
18  1127
19  1059
20  1163
21   982
22  1047
23   890
24   780
25  1124
26  1026
27  1010
28   183
29   163
30  1164
31  1044
32  1157
33   952
34   427
35   805
36  1106
37   881
38   424
39  1182
40  1027
41   468
42  1108
43  1155
44   823
45   788
46  1007
47  1102
48  1041

In [51]:
len(autores_treino)

49

##Visualização do planilha "views_treino" e inserção da coluna "tipo" para análise das matérias

In [52]:
views_treino

      data_audiencia  codmateria  audiencia
0         2020-10-01      138347        658
1         2020-10-01      124744         51
2         2020-10-01      204589      15514
3         2020-10-01      134805         12
4         2020-10-01      204581       1470
...              ...         ...        ...
53135     2021-08-19      206082          1
53136     2021-08-19      204665          1
53137     2021-08-19      216127          1
53138     2021-08-19      204710          1
53139     2021-08-19      211011          1

[53140 rows x 3 columns]

In [53]:
tipo = []
for x in range(len(views_treino)):
  for y in range(len(caract_treino)):
    if views_treino['codmateria'][x] == caract_treino['codmateria'][y]:
      tipo.append(caract_treino['tipo'][y])
      break

views_treino['tipo'] = tipo

In [54]:
views_treino

      data_audiencia  codmateria  audiencia  tipo
0         2020-10-01      138347        658     1
1         2020-10-01      124744         51     1
2         2020-10-01      204589      15514     1
3         2020-10-01      134805         12     1
4         2020-10-01      204581       1470     1
...              ...         ...        ...   ...
53135     2021-08-19      206082          1     0
53136     2021-08-19      204665          1     1
53137     2021-08-19      216127          1     0
53138     2021-08-19      204710          1     1
53139     2021-08-19      211011          1     0

[53140 rows x 4 columns]

##Agrupamento pela coluna "codmateria", cálculo do desvio padrão de cada matéria, o qual será usado para a elaboração do modelo por conta das características da "Hard News", a qual possui altos picos e baixas promovendo maior desvio padrão, e da "Evergreen", a qual por conta de ter pouca relação com o tempo tem a tendência de ter menor desvio padrão.

In [90]:
views_treino_por_codmateria = views_treino.groupby(by=['codmateria'])
std_views_treino_por_codmateria = views_treino_por_codmateria.std()
std_views_treino_por_codmateria

             audiencia  tipo
codmateria
116360       36.295006   0.0
124744       68.222111   0.0
129678       15.832711   0.0
134805      161.960838   0.0
137827      246.356853   0.0
...                ...   ...
215853       81.288420   0.0
215896      667.765222   0.0
215923       72.372349   0.0
216006       49.830020   0.0
216127      102.943518   0.0

[281 rows x 2 columns]

In [56]:
std_views_treino_por_codmateria = std_views_treino_por_codmateria.reset_index()
std_views_treino_por_codmateria['tipo'] = caract_treino['tipo']
std_views_treino_por_codmateria

     codmateria   audiencia  tipo
0        116360   36.295006     1
1        124744   68.222111     1
2        129678   15.832711     1
3        134805  161.960838     1
4        137827  246.356853     1
..          ...         ...   ...
276      215853   81.288420     0
277      215896  667.765222     0
278      215923   72.372349     0
279      216006   49.830020     0
280      216127  102.943518     0

[281 rows x 3 columns]

###Renomeação do nome da coluna {'audiencia':'desvio_padrao'}

In [57]:
std_views_treino_por_codmateria = std_views_treino_por_codmateria.rename(columns={'audiencia':'desvio_padrao'})
std_views_treino_por_codmateria

     codmateria  desvio_padrao  tipo
0        116360      36.295006     1
1        124744      68.222111     1
2        129678      15.832711     1
3        134805     161.960838     1
4        137827     246.356853     1
..          ...            ...   ...
276      215853      81.288420     0
277      215896     667.765222     0
278      215923      72.372349     0
279      216006      49.830020     0
280      216127     102.943518     0

[281 rows x 3 columns]

###Elaboração da média entre a categoria do desvio-padrão para ser colocada como critério para a elaboração do modelo

In [58]:
desvio_padrao_medio_views = std_views_treino_por_codmateria['desvio_padrao'].mean()
desvio_padrao_medio_views

449.6345512597099

###Classificação do desvio padrão de cada matéria

In [59]:
desvio_padrao_alto = []
for g in range(len(std_views_treino_por_codmateria)):
  if std_views_treino_por_codmateria['desvio_padrao'][g] <= desvio_padrao_medio_views:
    desvio_padrao_alto.append(0)
  else:
    desvio_padrao_alto.append(1)

std_views_treino_por_codmateria['desvio_padrao_alto'] = desvio_padrao_alto
std_views_treino_por_codmateria

     codmateria  desvio_padrao  tipo  desvio_padrao_alto
0        116360      36.295006     1                   0
1        124744      68.222111     1                   0
2        129678      15.832711     1                   0
3        134805     161.960838     1                   0
4        137827     246.356853     1                   0
..          ...            ...   ...                 ...
276      215853      81.288420     0                   0
277      215896     667.765222     0                   1
278      215923      72.372349     0                   0
279      216006      49.830020     0                   0
280      216127     102.943518     0                   0

[281 rows x 4 columns]

###Adição da coluna "desvio_padrao_alto" no "x_dummies" para a elaboração do modelo

In [60]:
x_dummies['desvio_padrao_alto'] = std_views_treino_por_codmateria['desvio_padrao_alto']

##Reordenamento das colunas do DataFrame "x_dummies" por ordem alfabética para padronização da ordem das colunas com o DataFrame "x_novas_dummies" e consequente realização bem sucedida do modelo

In [61]:
x_dummies = x_dummies.reindex(sorted(x_dummies.columns), axis=1)
x_dummies

     autor_1007  autor_1010  autor_1026  ...  tag_Segurança  tag_Software  tag_Voxel
0             0           0           0  ...              1             0          0
1             0           0           0  ...              0             0          0
2             0           0           0  ...              0             0          0
3             0           0           0  ...              0             0          0
4             0           0           0  ...              0             1          0
..          ...         ...         ...  ...            ...           ...        ...
276           0           0           0  ...              0             1          0
277           0           0           0  ...              0             0          0
278           0           0           0  ...              0             0          1
279           0           0           0  ...              0             0          0
280           0           0           0  ...              0             0          0

[281 rows x 64 columns]

##Transformação do DataFrame "x_dummies" e da Series "y_dummies" em array para a elaboração do modelo

In [62]:
x = x_dummies.values
y = y_dummies.values

In [63]:
print(x)

[[0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [64]:
print(y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

##Utilização da biblioteca Scikit-Learn para criação do modelo de classificação com o método "DecisionTreeClassifier", realizando a padronização das características com "StandardScaler", fazendo o treinamento e aplicação do modelo com "train_test_split", medindo a acurácia do modelo com accuracy_score e utilização da biblioteca NumPy para tornar estático o modelo através da função SEED

In [65]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

import numpy as np

SEED = 1
np.random.seed(SEED)

raw_treino_x, raw_teste_x, y_treino, y_teste = train_test_split(x, y, random_state = SEED, test_size = 0.3)

scaler = StandardScaler()
scaler.fit(raw_treino_x)
x_treino = scaler.transform(raw_treino_x)
x_teste = scaler.transform(raw_teste_x)

modelo = DecisionTreeClassifier()
modelo.fit(x_treino, y_treino)

resultado = modelo.predict(x_teste)

taxa_de_acerto = accuracy_score(y_teste, resultado) * 100
print('A acurácia foi de %.2f%%.' %taxa_de_acerto)

A acurácia foi de 77.65%.

##Criação do modelo bobo, através do "DummyClassifier" da biblioteca Scikit-Learn, para averiguação da qualidade do modelo criado

In [66]:
from sklearn.dummy import DummyClassifier

dummy_mostfrequent = DummyClassifier()
dummy_mostfrequent.fit(x_treino, y_treino)
acuracia = dummy_mostfrequent.score(x_teste, y_teste) * 100

print('A acurácia do dummy_mostfrequent foi de %.2f%%.' %acuracia)

A acurácia do dummy_mostfrequent foi de 57.65%.

/usr/local/lib/python3.7/dist-packages/sklearn/dummy.py:132: FutureWarning: The default value of strategy will change from stratified to prior in 0.24.
  "stratified to prior in 0.24.", FutureWarning)

##Visualização do DataFrame "caract_novas" e criação do DataFrame x_novas, o qual é o DataFrame das variáveis independentes

In [67]:
caract_novas.head()

   codmateria                 data_pub  ... publieditorial possuilinkafiliacao
0      204554  2020-10-01 11:00:01.913  ...              0                   0
1      204586  2020-10-01 09:30:01.583  ...              0                   0
2      204603  2020-10-01 11:00:01.913  ...              0                   0
3      204605  2020-10-01 11:14:55.043  ...              0                   0
4      204606  2020-10-01 11:34:57.950  ...              0                   0

[5 rows x 7 columns]

In [68]:
x_novas = caract_novas[['autor','tag', 'publieditorial', 'possuilinkafiliacao']]

##Transformação das variáveis categóricas, as quais estavam em formato string, em números binários para a elaboração do modelo de classificação, criando o DataFrame "x_novas_dummies"

In [69]:
x_novas_dummies = pd.get_dummies(x_novas)
x_novas_dummies

     publieditorial  possuilinkafiliacao  ...  tag_Software  tag_Voxel
0                 0                    0  ...             0          0
1                 0                    0  ...             0          1
2                 0                    0  ...             0          1
3                 0                    0  ...             0          0
4                 0                    0  ...             0          0
..              ...                  ...  ...           ...        ...
181               0                    0  ...             0          0
182               0                    0  ...             0          0
183               0                    0  ...             1          0
184               0                    0  ...             0          0
185               0                    0  ...             0          0

[186 rows x 50 columns]

##Criação de DataFrame com a lista de todos os autores ordenada pelo "autores_novas", através da junção dos autores dos DataFrames "caract_treino" e "caract_novas", para igualar o número de colunas do "x_dummies" e "x_novas_dummies", com o propósito de ser possível a execução do modelo de classificação e ser executado com maior precisão por conta da influência dos dados sobre os autores

In [70]:
for k in range(len(autores_treino)):
  if autores_treino['autor'][k] not in autores_novas:
    autores_novas.append(autores_treino['autor'][k])
    x_novas_dummies["autor_{}".format(autores_treino['autor'][k])] = 0

autores_novas = pd.Series(autores_novas).reset_index().drop(columns='index').rename(columns={0:'autor'})
autores_novas

   autor
0   1107
1    982
2   1054
3   1047
4    758
5    805
6   1027
7    775
8   1059
9    780
10  1170
11  1160
12  1166
13  1026
14   920
15  1010
16  1164
17   867
18   893
19   154
20  1124
21   932
22   163
23   759
24  1127
25  1163
26  1155
27   823
28   788
29  1106
30  1007
31  1102
32  1182
33  1041
34   890
35  1108
36   547
37   632
38   523
39   128
40   496
41   183
42  1044
43  1157
44   952
45   427
46   881
47   424
48   468

In [71]:
len(autores_novas)

49

##Visualização do planilha "views_novas" e inserção da coluna "tipo" para análise das matérias

In [72]:
views_novas

      data_audiencia  codmateria  audiencia
0         2020-10-01      204586       1750
1         2020-10-01      143848         12
2         2020-10-01      204603        718
3         2020-10-01      204554       4610
4         2020-10-01      204605        337
...              ...         ...        ...
37456     2021-08-19      208156          3
37457     2021-08-19      204702          1
37458     2021-08-19      211756          1
37459     2021-08-19      214741          1
37460     2021-08-19      204735          1

[37461 rows x 3 columns]

##Agrupamento pela coluna "codmateria" e cálculo do desvio padrão de cada matéria do DataFrame "views_novas_por_codmateria"

In [73]:
views_novas_por_codmateria = views_novas.groupby(by=['codmateria'])
std_views_novas_por_codmateria = views_novas_por_codmateria.std()
std_views_novas_por_codmateria

             audiencia
codmateria
143848      220.800437
204554      613.082570
204586      162.767083
204603       73.392444
204605       47.043818
...                ...
216077      326.911958
216082      892.896355
216107      664.181557
216111      800.501114
216123       48.822796

[186 rows x 1 columns]

In [74]:
std_views_novas_por_codmateria = std_views_novas_por_codmateria.reset_index()
std_views_novas_por_codmateria

     codmateria   audiencia
0        143848  220.800437
1        204554  613.082570
2        204586  162.767083
3        204603   73.392444
4        204605   47.043818
..          ...         ...
181      216077  326.911958
182      216082  892.896355
183      216107  664.181557
184      216111  800.501114
185      216123   48.822796

[186 rows x 2 columns]

###Renomeação do nome da coluna {'audiencia':'desvio_padrao'}

In [75]:
std_views_novas_por_codmateria = std_views_novas_por_codmateria.rename(columns={'audiencia':'desvio_padrao'})
std_views_novas_por_codmateria

     codmateria  desvio_padrao
0        143848     220.800437
1        204554     613.082570
2        204586     162.767083
3        204603      73.392444
4        204605      47.043818
..          ...            ...
181      216077     326.911958
182      216082     892.896355
183      216107     664.181557
184      216111     800.501114
185      216123      48.822796

[186 rows x 2 columns]

###Classificação do desvio padrão de cada matéria

In [76]:
desvio_padrao_alto = []
for g in range(len(std_views_novas_por_codmateria)):
  if std_views_novas_por_codmateria['desvio_padrao'][g] <= desvio_padrao_medio_views:
    desvio_padrao_alto.append(0)
  else:
    desvio_padrao_alto.append(1)

std_views_novas_por_codmateria['desvio_padrao_alto'] = desvio_padrao_alto
std_views_novas_por_codmateria

     codmateria  desvio_padrao  desvio_padrao_alto
0        143848     220.800437                   0
1        204554     613.082570                   1
2        204586     162.767083                   0
3        204603      73.392444                   0
4        204605      47.043818                   0
..          ...            ...                 ...
181      216077     326.911958                   0
182      216082     892.896355                   1
183      216107     664.181557                   1
184      216111     800.501114                   1
185      216123      48.822796                   0

[186 rows x 3 columns]

###Adição da coluna "desvio_padrao_alto" no "x_dummies" para a elaboração do modelo

In [77]:
x_novas_dummies['desvio_padrao_alto'] = std_views_novas_por_codmateria['desvio_padrao_alto']

##Reordenamento das colunas do DataFrame "x_novas_dummies" por ordem alfabética para padronização da ordem das colunas com o DataFrame "x_dummies" e consequente utilização bem sucedida do modelo

In [78]:
x_novas_dummies = x_novas_dummies.reindex(sorted(x_novas_dummies.columns), axis=1)
x_novas_dummies

     autor_1007  autor_1010  autor_1026  ...  tag_Segurança  tag_Software  tag_Voxel
0             0           0           0  ...              0             0          0
1             0           0           0  ...              0             0          1
2             0           0           0  ...              0             0          1
3             0           0           0  ...              0             0          0
4             0           0           0  ...              0             0          0
..          ...         ...         ...  ...            ...           ...        ...
181           0           0           0  ...              0             0          0
182           0           0           0  ...              0             0          0
183           0           0           0  ...              0             1          0
184           0           0           0  ...              0             0          0
185           0           0           0  ...              0             0          0

[186 rows x 64 columns]

##Transformação do DataFrame "x_novas_dummies" em array para a utilização do modelo criado

In [79]:
x_novas = x_novas_dummies.values

##Visualização do array "x_novas" e a dimensão do mesmo

In [80]:
print(x_novas)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [81]:
x_novas.shape

(186, 64)

##Classificação das matérias da planilha "caract_novas", a qual está em valor binário

In [82]:
modelo.predict(x_novas)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1])

##Inserção da classificação do "tipo" das matérias no DataFrame "caract_novas"

In [83]:
caract_novas['tipo'] = modelo.predict(x_novas)
caract_novas

     codmateria                 data_pub  ... possuilinkafiliacao tipo
0        204554  2020-10-01 11:00:01.913  ...                   0    1
1        204586  2020-10-01 09:30:01.583  ...                   0    1
2        204603  2020-10-01 11:00:01.913  ...                   0    1
3        204605  2020-10-01 11:14:55.043  ...                   0    1
4        204606  2020-10-01 11:34:57.950  ...                   0    1
..          ...                      ...  ...                 ...  ...
181      216077  2021-04-25 14:00:01.667  ...                   0    1
182      216082  2021-04-24 15:00:01.573  ...                   0    1
183      216107  2021-04-23 18:30:01.467  ...                   0    0
184      216111  2021-04-25 18:00:01.797  ...                   0    1
185      216123  2021-04-24 17:00:01.870  ...                   0    1

[186 rows x 8 columns]

##Conversão da classificação "tipo" de variáveis binárias para as strings "Evergreen" e "Hard News"

In [84]:
binario_tipo = {0 :'Evergreen',
                1 : 'Hard News'}

caract_novas['tipo'] = caract_novas['tipo'].map(binario_tipo)
caract_novas

     codmateria                 data_pub  ... possuilinkafiliacao       tipo
0        204554  2020-10-01 11:00:01.913  ...                   0  Hard News
1        204586  2020-10-01 09:30:01.583  ...                   0  Hard News
2        204603  2020-10-01 11:00:01.913  ...                   0  Hard News
3        204605  2020-10-01 11:14:55.043  ...                   0  Hard News
4        204606  2020-10-01 11:34:57.950  ...                   0  Hard News
..          ...                      ...  ...                 ...        ...
181      216077  2021-04-25 14:00:01.667  ...                   0  Hard News
182      216082  2021-04-24 15:00:01.573  ...                   0  Hard News
183      216107  2021-04-23 18:30:01.467  ...                   0  Evergreen
184      216111  2021-04-25 18:00:01.797  ...                   0  Hard News
185      216123  2021-04-24 17:00:01.870  ...                   0  Hard News

[186 rows x 8 columns]